# Домашнее задание 01-06

# 01-06

1) Импортировать numpy и написать версию

In [1]:
import numpy as np

print(np.__version__)

1.26.4


2) Создать нулевой вектор размера 10

In [2]:
v = np.zeros(10)

print(v)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


3) Создать вектор заполненный 7-ами размера 7

In [3]:
v = np.full(7, 7)

print(v)

[7 7 7 7 7 7 7]


4) Создать вектор заполненный четными числами от 10 до 100

In [4]:
v = np.arange(10, 101, 2)

print(v)

[ 10  12  14  16  18  20  22  24  26  28  30  32  34  36  38  40  42  44
  46  48  50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80
  82  84  86  88  90  92  94  96  98 100]


5) Создать массив случайных чисел и развернуть его задом наперёд

In [5]:
randomArr = np.random.rand(10)
randomArrReversed = np.flip(randomArr)

print(randomArr)
print(randomArrReversed)

[0.56267785 0.12390228 0.62905616 0.23415518 0.92628804 0.64949893
 0.86335964 0.67412417 0.60476324 0.89079275]
[0.89079275 0.60476324 0.67412417 0.86335964 0.64949893 0.92628804
 0.23415518 0.62905616 0.12390228 0.56267785]


6) Создать двумерную матрицу размера 3 на 3, заполненную числами от 0 до 9

In [6]:
m = np.arange(9).reshape(3, 3)

print(m)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7) Создать матрицу размера 4 на 4 с единицами на диагонали смещеной на один наверх.

In [7]:
m = np.zeros((4, 4))
np.fill_diagonal(m[0:, 1:], 1)

print(m)

[[0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]
 [0. 0. 0. 0.]]


8) Создать матрицу с числами в диапазоне от 1 до 4 по диагонали. В других ячейках матрицы должны быть семерки.

In [8]:
m = np.full((4, 4), 7)
np.fill_diagonal(m, [1, 2, 3, 4])

print(m)

[[1 7 7 7]
 [7 2 7 7]
 [7 7 3 7]
 [7 7 7 4]]


9) Создать матрицу размера 5 на 5 заполненную чилами от 0 до 4 в строках.

In [9]:
mStr = np.arange(5)
m = np.tile(mStr, (5, 1))

print(m)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


10) Создать матрицу случайных чисел размера 10 на 10 и отнять среднее по строкам из каждого элемента строки

In [12]:
m = np.random.randint(1, 11, size=(10, 10))
rowAverage = np.mean(m, axis=1)
newM = m - rowAverage[:, np.newaxis]

print(m)
print(newM)

[[ 4  2  1  2  7  8  2  4  6  2]
 [ 9  3  6  4  2  7  2  5 10  3]
 [ 7  9  1  9  7  1  1  8  5  7]
 [ 3  9  3  1  7  1  9  7  9  3]
 [ 8  6  2 10  8  2  4  6  3  8]
 [ 5  8  1  1  9  5  1  3 10  5]
 [10  9  7  2  5  4  5  3  5  3]
 [ 5  5  5  9  4  5  2  8  8  5]
 [ 4  1  4  6  8  5  2  2  4  9]
 [ 8  4  3  5  7  7 10 10  6  8]]
[[ 0.2 -1.8 -2.8 -1.8  3.2  4.2 -1.8  0.2  2.2 -1.8]
 [ 3.9 -2.1  0.9 -1.1 -3.1  1.9 -3.1 -0.1  4.9 -2.1]
 [ 1.5  3.5 -4.5  3.5  1.5 -4.5 -4.5  2.5 -0.5  1.5]
 [-2.2  3.8 -2.2 -4.2  1.8 -4.2  3.8  1.8  3.8 -2.2]
 [ 2.3  0.3 -3.7  4.3  2.3 -3.7 -1.7  0.3 -2.7  2.3]
 [ 0.2  3.2 -3.8 -3.8  4.2  0.2 -3.8 -1.8  5.2  0.2]
 [ 4.7  3.7  1.7 -3.3 -0.3 -1.3 -0.3 -2.3 -0.3 -2.3]
 [-0.6 -0.6 -0.6  3.4 -1.6 -0.6 -3.6  2.4  2.4 -0.6]
 [-0.5 -3.5 -0.5  1.5  3.5  0.5 -2.5 -2.5 -0.5  4.5]
 [ 1.2 -2.8 -3.8 -1.8  0.2  0.2  3.2  3.2 -0.8  1.2]]


11) Создать матрицу случайных чисел размера 10 на 10 и отнять медиану по столбцам из каждого элемента столбца  

In [15]:
m = np.random.randint(1, 11, size=(10, 10))
colMedians = np.median(m, axis=0)
newM = m - colMedians

print(m)
print(newM)

[[ 1  8  2  3  9  2  7  4  1  4]
 [ 6  1  6  6  2  9  1  6  4  8]
 [ 4  9  1  6  2  1 10  4  2  2]
 [ 1  4  1  8  6  1  6  8  6  8]
 [ 6 10  4  5  2  3  1 10  1  1]
 [ 9  3  1  5  5  3  4  1  6 10]
 [ 8  2  7  3  1  2 10  2  7  5]
 [ 8  5  2  4  5  6  8 10  6  5]
 [ 1  2  3 10  8  5  6  6  7  8]
 [ 7  5  5  9  5  8  7  2  2  2]]
[[-5.   3.5 -0.5 -2.5  4.  -1.   0.5 -1.  -4.  -1. ]
 [ 0.  -3.5  3.5  0.5 -3.   6.  -5.5  1.  -1.   3. ]
 [-2.   4.5 -1.5  0.5 -3.  -2.   3.5 -1.  -3.  -3. ]
 [-5.  -0.5 -1.5  2.5  1.  -2.  -0.5  3.   1.   3. ]
 [ 0.   5.5  1.5 -0.5 -3.   0.  -5.5  5.  -4.  -4. ]
 [ 3.  -1.5 -1.5 -0.5  0.   0.  -2.5 -4.   1.   5. ]
 [ 2.  -2.5  4.5 -2.5 -4.  -1.   3.5 -3.   2.   0. ]
 [ 2.   0.5 -0.5 -1.5  0.   3.   1.5  5.   1.   0. ]
 [-5.  -2.5  0.5  4.5  3.   2.  -0.5  1.   2.   3. ]
 [ 1.   0.5  2.5  3.5  0.   5.   0.5 -3.  -3.  -3. ]]


12) Создать матрицу случайных чисел 5x5. Добавить к ней столбецы максимумов и минимумов по строкам. Получится матрица 5x7.  

In [14]:
m = np.random.randint(1, 11, size=(5, 5))
rowMax = np.max(m, axis=1)
rowMin = np.min(m, axis=1)
newM = np.column_stack((m, rowMax, rowMin))

print(m)
print(newM)

[[ 5  1  6  7  6]
 [ 8  6  5  7  4]
 [ 1  7  1  2  1]
 [ 2  3  2  2  6]
 [ 1  4  3  9 10]]
[[ 5  1  6  7  6  7  1]
 [ 8  6  5  7  4  8  4]
 [ 1  7  1  2  1  7  1]
 [ 2  3  2  2  6  6  2]
 [ 1  4  3  9 10 10  1]]


13) Вектор чисел от 1 до 51 преобразовать в вектор нечетных чисел и в вектор четных чисел, поменять их размерности, чтобы получились две матрица. Найти произведение этих матриц. Найти обратную матрицу эётого произведения.  

In [16]:
v = np.arange(1, 52)

oddV = v[v % 2 != 0]
evenV = v[v % 2 == 0]

oddM = oddV.reshape(26, 1)
evenM = evenV.reshape(1, 25)
# НОД у 25 и 26 - 1, т. к. числа взаимно простые

productM = np.dot(oddM, evenM)

# произведение матриц - неквадратная матрица => обратную не можем найти.

print(oddV, evenV)
print(oddM)
print(evenM)
print(productM)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51] [ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50]
[[ 1]
 [ 3]
 [ 5]
 [ 7]
 [ 9]
 [11]
 [13]
 [15]
 [17]
 [19]
 [21]
 [23]
 [25]
 [27]
 [29]
 [31]
 [33]
 [35]
 [37]
 [39]
 [41]
 [43]
 [45]
 [47]
 [49]
 [51]]
[[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
  50]]
[[   2    4    6    8   10   12   14   16   18   20   22   24   26   28
    30   32   34   36   38   40   42   44   46   48   50]
 [   6   12   18   24   30   36   42   48   54   60   66   72   78   84
    90   96  102  108  114  120  126  132  138  144  150]
 [  10   20   30   40   50   60   70   80   90  100  110  120  130  140
   150  160  170  180  190  200  210  220  230  240  250]
 [  14   28   42   56   70   84   98  112  126  140  154  168  182  196
   210  224  238  252  266  280  294  308  322  336  350]
 [  18   36   54   72   90  108  126  144  162  180  198  216  234  252
   270  288

14) Создать 8x8 матрицу и заполнить её в шахматном порядке нулями и единицами.

In [17]:
board = np.zeros((8, 8))
board[1::2, ::2] = 1
board[::2, 1::2] = 1

print(board)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]
